openapi: 3.0.1
info:
  title: I_Constraint_Management_Insurant
  description: |
    This interface provides access to the service **Constraint Management** of a personal health 
    record for insurants and representatives.<br/>
    
    **General conditions**:</br> 
    For all operations if applicable:
    - a section _Client_ in operation descriptions covers recommendations (informative) for clients.
    - a section _Provider_ in operation descriptions covers requirements for the server side. 
    - error responses may be extended by helpful information about the error condition in _errorDetail_

    **Prereqisites**:</br>
    The Health Record System shall provide 
    - name
    - role ((profession-)oid)
    - identifier (telematik-id or kvnr)
    - indication of a valid entitlement 
    
    of the current user (requestor) for evaluation in operations.

    Operations mandating a valid entitlement implicitely mandate use of a VAU-channel
    and a valid ID-Token. If one of these conditions is not met, then the response
    of the (aborted) operation shall always be '403': 'notEntitled'. 

    **Retry interval**:</br>
    The following retry intervals are suggested in case of an error response:<br>
    - '409' Conflict (statusMismatch).
      - approx. 24 hours
    - '500' Internal Error
      - approx. 10 minutes

    **User Agent**:</br>
    The user agent information (x-useragent) is part of any request, even if 
    not essentially required for the operation (e.g. raw-data collection), and
    may be considered for provider internal use. 

    **Log-Entries**
    Whenever a _Postcondition_ mandates a log-entry, this entry shall contain
    data as defined in A_24887*.

  contact:
    name: gematik GmbH
    email: epa@gematik.de
    url: 'http://www.gematik.de'

  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

  version: 0.0.1
  
  # version history:
  # ----------------
  # version 0.0.1
  #   - initial version for review

servers:
  - url: https://epa-hst1.prod.epa4all.de/api

tags:
  - name: ConstraintManagement
    description: |
      Constraint Management allow to configure the deny policies of a health record by 
      setting or deleting constraints (assignments of a deny policy).</br>
      An assignment may be related to a single document, a folder or a category. Any document affected
      by an assigment will be either hidden to users of the deny policy affected user roles or
      to a dedicated user only.</br>
      
      Deny Policies are availble in two flavours:
      - a **General Deny Policy**. Each document hidden by assignments of this policy is not visible
      for any user of any deny policy affected user role.
      - a **User-specific Deny Policy**. Each document hidden by assignments of this policy is not visible
      for the addressed user (telematik-id) of the deny policy affected user role.
      
      The assignments of the deny policies hide documents for the XDS Document Service only. Assigments 
      related to folders or categories hide all contained documents (not the folder / category)

      **Allowed user groups/ roles**:</br> 
      The deny policies affect the following user groups (roles). User-specific Deny Policy
      assignments are only applicable for users of those roles. The following list of oids is for information 
      only and may be incomplete, the normative requirement is defined in A_24306-*
      - oid_praxis_arzt
      - oid_krankenhaus
      - oid_institution-vorsorge-reha
      - oid_zahnarztpraxis
      - oid_öffentliche_apotheke
      - oid_praxis_psychotherapeut
      - oid_institution-pflege
      - oid_institution-geburtshilfe
      - oid_praxis-physiotherapeut
      - oid_institution-oegd
      - oid_institution-arbeitsmedizin

      **Restricted categories and folders**:</br>
      Some categories/folders of a health record may contain MIOs or structured documents represented by more 
      than one XDS document (document collections, e.g. category _vaccination_). Hiding single documents 
      of such MIOs or structured documents would take the contained information out of context. This should 
      be avoided, thus hiding single documents is not supported in this case.</br>
      The following list shows categories with this restriction and is for information only and 
      may be incomplete. The normative requirement to avoid hiding of single documents applies
      for any folder with type = "uniform" or "mixed" (see 
      src/implementation_guides on GitHub/gematik/api-epa).
      
      - dentalrecord
      - childsrecord
      - mothersrecord
      - vaccination

      **Remarks**:</br>
      - Assignments for the General Deny Policy may also be applied internally
      by the XDS document service after evaluation of confidentialityCode metadata 
      in a document provide operation.
      - Assignments of the policies are deleted internally in case a referenced _document_
      or folder is deleted from the document management.

paths:
  /constraintmanagement/v1:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/useragent'      
    get:
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/policyType'
        - $ref: '#/components/parameters/for'
        - $ref: '#/components/parameters/categories'
        - $ref: '#/components/parameters/documents'
        - $ref: '#/components/parameters/folders'
        - $ref: '#/components/parameters/telematikid'
        - $ref: '#/components/parameters/oid'
      tags:
        - ConstraintManagement
      operationId: getDenyPolicyAssignments
      summary: (getDenyPolicyAssignments) get a list of actual set deny policy assignments
      description: |
        Get a combined list of actual set assignments of the general deny policy and the user-
        specific deny policy.</br>  
        This operation is limited to entitled users of role oid_versicherter.
        
        **Client**:</br>
        A client shall consider the schema for 'Queries' and 'Paging' (see below).

        **Provider**:</br>
        The returned list shall contain only assignments matching the query parameters of both 
        deny policies (general and user-specific).</br>

        Paging:</br>
        _offset_ and _limit_ parameters shall be related to the amount of assignments matching the query and only occure 
        once in a request. Default shall be for _offset_ = 0 and for _limit_ = 50 (this shall also be the maximum _limit_).
        The applied _offset_ and _limit_ and the total amount of matching assignments shall be part of the response.</br>
        _offset_ shall be a "page-offset" and is related to _limit_ which is the "page-size", e.g. if total amount of 
        matching assignments is 75, than _offset_ = 0 with _limit_ = 40 return result 1 to 40 and _offset_ = 1 with _limit_ 
        = 40 return result 41 to 75 and _offset_ = 2 with _limit_ = 40 return an 'empty' result.  
        
        Queries:</br>
        Different query parameters (name) shall be applied as logical AND, multiple query strings (same name) 
        as OR. Default for all query parameters is ("*").
        Queries for _folders_ shall use urn.encoded uuids (use urn:uuid:65e2a7a3-b46f-40f4-b821-4efc23a57400 instead 
        of 65e2a7a3-b46f-40f4-b821-4efc23a57400).</br>
        Queries for _documents_ shall use identifiers matching the referenceId schema 
        'uniqueID^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId' ('uniqueId' equals also the documentEntry.uniqueId (a uuid)). 

        Queries for _tid_ and _oid_ shall consider the user-specific deny policy assignments only.

        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_versicherter_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | none ||

      responses:
        '200':
          description: Ok. Returns a list of policy assignments
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: object
                    properties:
                      offset:
                        description: applied offset to matching results
                        type: integer
                      limit: 
                        description: applied limit to matching results
                        type: integer
                      totalMatching:
                        description: total amount of matching results in policies
                        type: integer
                  assignments:
                    type: array
                    items:
                      allOf:
                      - $ref: '#/components/schemas/DenyPolicyAssignmentResponseType'
              examples:
                getAll:
                  $ref: '#/components/examples/Get_AllPolicyAssignments'
                FilterPolicyType:
                  $ref: '#/components/examples/Get_QueryForPolicyType'
                FilterCategory:
                  $ref: '#/components/examples/Get_QueryForCategory'
                FilterTID:
                  $ref: '#/components/examples/Get_QueryForTID'
                FilterOid:
                  $ref: '#/components/examples/Get_QueryForRole'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: "#/components/responses/Error404NotFound"
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

    post:
      tags:
        - ConstraintManagement
      operationId: setDenyPolicyAssignment
      summary: (setDenyPolicyAssignment) set a new deny policy assignment
      description: |
        Set a new assignment for a deny policy (general or user-specific).</br>
        This operation is limited to entitled users of role oid_versicherter.

        **Client**:</br>
        A client shall set assigments for existing resources only.</br>
        A client shall set assignments _folder_ for dynamic folders only (static 
        folders are assigned via _category_ only).</br> 
        A client shall not set assignments _document_ for a restricted category/folder.
        A client shall set assignments for content of the XDS document service only.

        **Provider**:</br>
        A new assignment shall use:</br>
        - a _category_ entry addressed by a technical identifier string (e.g. 'vaccination'), or</br>
        - a _folder_ entry addressed by folder.EntryUUID (urn-encoded uuid), or</br>
        - a _document_ entry addressed by an identifier 'uniqueID^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId' as 
        used in documentEntry.referenceIdList with 'uniqueId' the symbolic uuid of documentEntry.uniqueID.

        Each new valid assigment shall be extended by a uuid (assignementId) for identification
        by the server. This uuid shall be unique in context of deny policies for the health record.

        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_versicherter_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Addressed _document_ or _folder_ does not exist | 404 | noResource ||
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | The assignment parameter _oid_ is not in the list of allowd oids | 409 | requestMismatch ||
        | An addressed _folder_ is not of type _dynamic_ | 409 | requestMismatch ||
        | An addressed _document_ is part of a restricted category or folder | 409 | requestMismatch ||
        | An addressed _category_ is not part of the XDS Document Service | 409 | requestMismatch ||
        | The assignment does yet exist | 409 | requestMismatch | avoid duplicates ||
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | The policy assignment is extended with the assignmentId and stored in SecureDataStorage ||
        | A log-entry for the operation exists | all operation results |
        | The raw-data of the operation is collected and associated to _useragent_ | for any operation result according to gemSpec_PerfUC_B4.x |

      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/DenyPolicyAssignmentType'
            examples:
              GDPolicyAssignmentForCategories:
                $ref: '#/components/examples/Add_category_to_general_deny_policy'
              GDPolicyAssignmentForDocuments:
                $ref: '#/components/examples/Add_document_to_general_deny_policy'
              GDPolicyAssignmentForFolders:
                $ref: '#/components/examples/Add_folder_to_general_deny_policy'
              USDPolicyAssignmentForCategories:
                $ref: '#/components/examples/Add_category_to_user-specific_deny_policy'
              USDPolicyAssignmentForDocuments:
                $ref: '#/components/examples/Add_document_to_user-specific_deny_policy'
              USDPolicyAssignmentForFolders:
                $ref: '#/components/examples/Add_folder_to_user-specific_deny_policy'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/DenyPolicyAssignmentResponseType'
              examples:
                GDPolicyAssignmentForCategories:
                  $ref: '#/components/examples/Response_category_to_general_deny_policy'
                GDPolicyAssignmentForDocuments:
                  $ref: '#/components/examples/Response_document_to_general_deny_policy'
                GDPolicyAssignmentForFolders:
                  $ref: '#/components/examples/Response_folder_to_general_deny_policy'
                USDPolicyAssignmentForCategories:
                  $ref: '#/components/examples/Response_category_to_user-specific_deny_policy'
                USDPolicyAssignmentForDocuments:
                  $ref: '#/components/examples/Response_document_to_user-specific_deny_policy'
                USDPolicyAssignmentForFolders:
                  $ref: '#/components/examples/Response_folder_to_user-specific_deny_policy'
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'
  
  /constraintmanagement/v1/{assignmentId}:
    parameters:
      - $ref: '#/components/parameters/insurantid'
      - $ref: '#/components/parameters/assignmentId'
      - $ref: '#/components/parameters/useragent'      
    delete:
      tags:
        - ConstraintManagement
      operationId: deleteDenyPolicyAssignment
      summary: (deleteDenyPolicyAssignment) delete a specific deny policy assignment
      description: |
        Delete one existing assignment of a deny policy (general or user-specific).</br>
        This operation is limited to entitled users of role oid_versicherter.

        **Client**:</br>
        no recommendations.

        **Provider**:</br>
        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 204 |||
        | Request does not match schema | 400 | malformedRequest ||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not _oid_versicherter_ | 403 | invalidOid ||
        | Health record does not exist | 404 | noHealthRecord | _insurantid_ unknown |
        | Assignement (_assignmentid_) does not exist | 404 | noResource ||
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | Any other error | 500 | internalError | (see 'Retry interval') |

         </br>
        | Postconditions                        | Remarks |
        |---------------------------------------|---------|
        | The addressed assignment is removed from the associated policy ||
        | A log-entry for the operation exists | all operation results |

      responses:
        '204':
          description: OK. Assignment deleted
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: '#/components/responses/Error404NotFound'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'

components:
  responses:
    Error400BadRequest:
      description: Bad Request.
      content:
        application/json:
          example:
            errorCode: malformedRequest
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error403Forbidden:
      description: Forbidden.
      content:
        application/json:
          example:
            errorCode: notEntitled
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error404NotFound:
      description: Not found.
      content:
        application/json:
          example:
            errorCode: noResource
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error409Conflict:
      description: Conflict.
      content:
        application/json:
          examples:
            statusMismatch:
              value:
                errorCode: statusMismatch
            requestMismatch:
              value:
                errorCode: requestMismatch
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error500InternalError:
      description: Internal Server Error
      content:
        application/json:
          example:
            errorCode: internalError
          schema:
            $ref: '#/components/schemas/ErrorType'

  parameters:
    insurantid:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: '#/components/schemas/InsurantIdType'
    useragent:
      name: x-useragent
      in: header
      description: user agent information
      required: true
      schema:
        $ref: '#/components/schemas/UserAgentType'
    assignmentId:
      name: assignmentId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/AssignmentIdType'
    limit:
      name: limit
      in: query
      description: Limits the number of matching items in a response ('pagesize', default and max = 50).
      schema:
        type: integer
        maximum: 50
        minimum: 1
    offset:
      name: offset
      in: query
      description: Specifies skipped matching pages ('pagesize' == limit), (default = 0).
      schema:
        type: integer
    policyType:
      name: policyType
      in: query
      description: Query the deny policy assignments for general deny policy assignment (gdp) or user-specific deny policy assignments (usdp).
      schema:
        $ref: '#/components/schemas/PolicyType'
    for:
      name: for
      in: query
      description: Query for deny policy assignments hiding categories or documents or folders
      schema:
        $ref: '#/components/schemas/ForType'
    categories:
      name: parameters.categoryId
      in: query
      description: Query for deny policy assignment hiding a specific category.
      schema:
        $ref: '#/components/schemas/CategoryIdType'
    documents:
      name: parameters.rootDocumentId
      in: query
      description: Query for deny policy assignment hiding a specific document.
      schema:
        $ref: '#/components/schemas/RootDocumentIdType'
    folders:
      name: parameters.folderUUID
      in: query
      description: Query for deny policy assignment hiding a specific folder.
      schema:
        $ref: '#/components/schemas/UuidType'
    telematikid:
      name: parameters.tid
      in: query
      description: Query for deny policy assignments related to a specific telematik-id (considers user-specific deny policy only)
      schema:
        $ref: '#/components/schemas/TelematikIdType'
    oid:
      name: parameters.oid
      in: query
      description: 'Query for deny policy assignments related to a specific role (professionOID, considers user-specific deny policy only)'
      schema:
        $ref: '#/components/schemas/OidType'
  schemas:
    AssignmentIdType:
      description: Server-assigned unique uuid of a particular deny policy assignment
      type: string
      format: uuid
      example: fa2bc929-f6c9-419f-ae75-cea040927651
    TelematikIdType:
      description: A Telematik-ID
      type: string
      pattern: '[0-9]{1}[-]{1}\d{1,126}$'
      example: 2-883110000118994
    PolicyType:
      description: Select a Deny Policy
      type: string
      enum:
        - gdp
        - usdp
      example: gdp
    ForType:
      description: Select an assignemnt type
      type: string
      enum:
        - category
        - document
        - folder
      example: category
    OidType:
      description: A professionOID
      type: string
      pattern: '([0-2])((\.0)|(\.[1-9][0-9]*))*$'
      example: '1.2.276.0.76.4.50'
    UuidType:
      description: An urn-encoded UUID
      type: string
      example: urn:uuid:4fa70820-2384-4001-80a9-7bbd5e085efb
    RootDocumentIdType:
      description: |
        A CXi style identifier with schema 'uniqueID^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId' with symbolic UUID as uniqueId
      type: string
      example: 4fa70820-2384-4001-80a9-7bbd5e085efb^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
    CategoryIdType:
      description: A technical identifier of a category
      type: string
      enum:
        - reports
        - emp
        - nfd
        - eab
        - dentalrecord
        - childsrecord
        - pregnancy_childbirth
        - vaccination
        - patient
        - receipt
        - care
        - eau
        - rehab
        - other
    DenyPolicyAssignmentType:
      description: Basic type for a deny policy assignments.
      oneOf:
        - $ref: '#/components/schemas/GDPolicyAssignmentForDocumentType'
        - $ref: '#/components/schemas/GDPolicyAssignmentForFolderType'
        - $ref: '#/components/schemas/GDPolicyAssignmentForCategoryType'
        - $ref: '#/components/schemas/USDPolicyAssignmentForDocumentType'
        - $ref: '#/components/schemas/USDPolicyAssignmentForFolderType'
        - $ref: '#/components/schemas/USDPolicyAssignmentForCategoryType'
    DenyPolicyAssignmentResponseType:
      allOf:
        - type: object
          properties:
            assignmentId:
              allOf:
                - $ref: '#/components/schemas/AssignmentIdType'
        - oneOf:
            - $ref: '#/components/schemas/GDPolicyAssignmentForDocumentType'
            - $ref: '#/components/schemas/GDPolicyAssignmentForFolderType'
            - $ref: '#/components/schemas/GDPolicyAssignmentForCategoryType'
            - $ref: '#/components/schemas/USDPolicyAssignmentForDocumentType'
            - $ref: '#/components/schemas/USDPolicyAssignmentForFolderType'
            - $ref: '#/components/schemas/USDPolicyAssignmentForCategoryType'
    GDPolicyAssignmentForCategoryType:
      description: Global deny policy assigment for a single category.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - gdp
        for:
          type: string
          enum:
            - category
        parameters:
          type: object
          required:
            - categoryId
          properties:
            categoryId:
              allOf:
                - $ref: '#/components/schemas/CategoryIdType'
              description: technical identifier of category
          additionalProperties: false
      additionalProperties: false
    GDPolicyAssignmentForDocumentType:
      description: Global deny policy assigment for a single document.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - gdp
        for:
          type: string
          enum:
            - document
        parameters:
          type: object
          required:
            - rootDocumentId
          properties:
            rootDocumentId:
              allOf:
                - $ref: '#/components/schemas/RootDocumentIdType'
              description: rootDocumentUniqueId from DocumentEntry.referenceIdList 
          additionalProperties: false
      additionalProperties: false
    GDPolicyAssignmentForFolderType:
      description: Global deny policy assigment for a single folder.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - gdp
        for:
          type: string
          enum:
            - folder
        parameters:
          type: object
          required:
            - folderUUID
          properties:
            folderUUID:
              allOf:
                - $ref: '#/components/schemas/UuidType'
              description: Folder.entryUUID
          additionalProperties: false
      additionalProperties: false
    USDPolicyAssignmentForDocumentType:
      description: User-specific deny policy assigment for a single document.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - usdp
        for:
          type: string
          enum:
            - document
        parameters:
          type: object
          required:
            - tid
            - oid
            - displayName
            - rootDocumentId
          properties:
            tid:
              allOf:
                - $ref: '#/components/schemas/TelematikIdType'
              description: Telematik-Id of related user
            oid:
              allOf:
                - $ref: '#/components/schemas/OidType'
              description: profession-oid of related user
            displayName:
              description: Name of related user
              type: string
            rootDocumentId:
              allOf:
                - $ref: '#/components/schemas/RootDocumentIdType'
              description: rootDocumentUniqueId from DocumentEntry.referenceIdList 
          additionalProperties: false
      additionalProperties: false
    USDPolicyAssignmentForCategoryType:
      description: User-specific deny policy assigment for a single category.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - usdp
        for:
          type: string
          enum:
            - category
        parameters:
          type: object
          required:
            - tid
            - oid
            - displayName
            - categoryId
          properties:
            tid:
              allOf:
                - $ref: '#/components/schemas/TelematikIdType'
              description: Telematik-Id of related user
            oid:
              allOf:
                - $ref: '#/components/schemas/OidType'
              description: profession-oid of related user
            displayName:
              description: Name of related user
              type: string
            categoryId:
              allOf:
                - $ref: '#/components/schemas/CategoryIdType'
              description: technical identifier of category
          additionalProperties: false
      additionalProperties: false
    USDPolicyAssignmentForFolderType:
      description: User-specific deny policy assigment for a single folder.
      type: object
      properties:
        policyType:
          type: string
          enum:
            - usdp
        for:
          type: string
          enum:
            - folder
        parameters:
          type: object
          required:
            - tid
            - oid
            - displayName
            - folderUUID
          properties:
            tid:
              allOf:
                - $ref: '#/components/schemas/TelematikIdType'
              description: Telematik-Id of related user
            oid:
              allOf:
                - $ref: '#/components/schemas/OidType'
              description: profession-oid of related user
            displayName:
              description: Name of related user
              type: string
            folderUUID:
              allOf:
                - $ref: '#/components/schemas/UuidType'
              description: Folder.entryUUID
          additionalProperties: false
      additionalProperties: false
    UserAgentType:
      description: "Information about client software with: ClientId(20 characters) + / + VersionNumber (1 to 15 characters)."
      type: string
      pattern: '^[a-zA-Z0-9]{20}\/[a-zA-Z0-9\-\.]{1,15}$'
      example: CLIENTID1234567890AB/2.1.12-45
    InsurantIdType:
      type: string
      description: |-
        The health record identifier. 
        For today the record identifier equals the insurant id (kvnr).
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    ErrorType:
      description: Error object with additional information about the occurred error
      type: object
      properties:
        errorCode:
          description: Error condition specifier
          type: string
        errorDetail:
          description: Additional details regarding the error condition (if applicable)
          type: string
      required:
        - errorCode

  examples:
    Add_category_to_general_deny_policy:
      summary: Set an assigment for a category in General Deny Policy
      value:
        policyType: gdp
        for: category
        parameters:
          categoryId: patientdoc
    Response_category_to_general_deny_policy:
      summary: Response of assigment for a category in General Deny Policy
      value:
        assignmentId: ddf19ee6-e831-430d-893f-71d219ac12a0
        policyType: gdp
        for: category
        parameters:
          categoryId: patientdoc
    Add_document_to_general_deny_policy:
      summary: Set an assigment for a document in General Deny Policy
      value:
        policyType: gdp
        for: document
        parameters:
          rootDocumentId: 0f70653d-d5f4-46f0-99e1-b6af92eea2b6^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
    Response_document_to_general_deny_policy:
      summary: Response of assigment for a document in General Deny Policy
      value:
        assignmentId: b4593ccc-e29e-47b0-89fc-1ee80df188aa
        policyType: gdp
        for: document
        parameters:
          rootDocumentId: 0f70653d-d5f4-46f0-99e1-b6af92eea2b6^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
    Add_folder_to_general_deny_policy:
      summary: Set an assigment for a folder in General Deny Policy
      value:
        policyType: gdp
        for: folder
        parameters:
          folderUUID: 84d92a96-3585-4ad3-94b1-c4f3dbe87176
    Response_folder_to_general_deny_policy:
      summary: Response of assigment for a folder in General Deny Policy
      value:
        assignmentId: 8130eafa-a4fa-4337-aedb-6019b66e48f3
        policyType: gdp
        for: folder
        parameters:
          folderUUID: 84d92a96-3585-4ad3-94b1-c4f3dbe87176
    Add_category_to_user-specific_deny_policy:
      summary: Set an assigment for a category in User-specific Deny Policy
      value:
        policyType: uspd
        for: category
        parameters:
          tid: 2-883110000092414
          oid: 1.2.276.0.76.4.51
          displayName: Zahnarztpraxis Norbert Freiherr Schomaker
          categoryId: dentalrecord
    Response_category_to_user-specific_deny_policy:
      summary: Response of assigment for a category in User-specific Deny Policy
      value:
        assignmentId: 21694fb0-3019-4824-a34e-d4e1c031470e
        policyType: uspd
        for: category
        parameters:
          tid: 2-883110000092414
          oid: 1.2.276.0.76.4.51
          displayName: Zahnarztpraxis Norbert Freiherr Schomaker
          categoryId: dentalrecord
    Add_document_to_user-specific_deny_policy:
      summary: Set an assigment for a document in User-specific Deny Policy
      value:
        policyType: usdp
        for: document
        parameters:
          tid: 1-883110000092404
          oid: 1.2.276.0.76.4.50
          displayName: Praxis Dr. Annamaria Heckhausén
          rootDocumentId: c4e17b20-ecee-4261-a51d-396b8e81bc27^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
    Response_document_to_user-specific_deny_policy:
      summary: Response of assigment for a document in User-specific Deny Policy
      value:
        assignmentId: 74343201-e669-4675-8414-3ce517220a3b
        policyType: usdp
        for: document
        parameters:
          tid: 1-883110000092404
          oid: 1.2.276.0.76.4.50
          displayName: Praxis Dr. Annamaria Heckhausén
          rootDocumentId: c4e17b20-ecee-4261-a51d-396b8e81bc27^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
    Add_folder_to_user-specific_deny_policy:
      summary: Set an assigment for a folder in User-specific Deny Policy
      value:
        policyType: usdp
        for: folder
        parameters:
          tid: 1-883110000092404
          oid: 1.2.276.0.76.4.50
          displayName: Praxis Dr. Annamaria Heckhausén
          folderUUID: f9929ed6-1119-4dea-a48a-1cfe8117f7b7
    Response_folder_to_user-specific_deny_policy:
      summary: Response of assigment for a folder in User-specific Deny Policy
      value:
        assignmentId: 7730578d-9380-47d6-ae82-d2c47ca399af
        policyType: usdp
        for: folder
        parameters:
          tid: 1-883110000092404
          oid: 1.2.276.0.76.4.50
          displayName: Praxis Dr. Annamaria Heckhausén
          folderUUID: f9929ed6-1119-4dea-a48a-1cfe8117f7b7
    Get_AllPolicyAssignments:
      summary: Get all Deny Policy assignments.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 6
        assignments:
          - assignmentId: ddf19ee6-e831-430d-893f-71d219ac12a0
            policyType: gdp
            for: category
            parameters:
              categoryId: patientdoc
          - assignmentId: b4593ccc-e29e-47b0-89fc-1ee80df188aa
            policyType: gdp
            for: document
            parameters:
              rootDocumentId: 0f70653d-d5f4-46f0-99e1-b6af92eea2b6^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
          - assignmentId: 8130eafa-a4fa-4337-aedb-6019b66e48f3
            policyType: gdp
            for: folder
            parameters:
              folderUUID: urn:uuid:84d92a96-3585-4ad3-94b1-c4f3dbe87176
          - assignmentId: 21694fb0-3019-4824-a34e-d4e1c031470e
            policyType: uspd
            for: category
            parameters:
              tid: 2-883110000092414
              oid: 1.2.276.0.76.4.51
              displayName: Zahnarztpraxis Norbert Freiherr Schomaker
              categoryId: dentalrecord
          - assignmentId: 74343201-e669-4675-8414-3ce517220a3b
            policyType: usdp
            for: document
            parameters:
              tid: 1-883110000092404
              oid: 1.2.276.0.76.4.50
              displayName: Praxis Dr. Annamaria Heckhausén
              rootDocumentId: c4e17b20-ecee-4261-a51d-396b8e81bc27^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
          - assignmentId: 7730578d-9380-47d6-ae82-d2c47ca399af
            policyType: usdp
            for: folder
            parameters:
              tid: 1-883110000092404
              oid: 1.2.276.0.76.4.50
              displayName: Praxis Dr. Annamaria Heckhausén
              folderUUID: urn:uuid:f9929ed6-1119-4dea-a48a-1cfe8117f7b7
    Get_QueryForPolicyType:
      summary: Get all Deny Policy assignments for the policyType gdp.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 3
        assignments:
          - assignmentId: ddf19ee6-e831-430d-893f-71d219ac12a0
            policyType: gdp
            for: category
            parameters:
              categoryId: patientdoc
          - assignmentId: b4593ccc-e29e-47b0-89fc-1ee80df188aa
            policyType: gdp
            for: document
            parameters:
              rootDocumentId: 0f70653d-d5f4-46f0-99e1-b6af92eea2b6^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
          - assignmentId: 8130eafa-a4fa-4337-aedb-6019b66e48f3
            policyType: gdp
            for: folder
            parameters:
              folderUUID: urn:uuid:84d92a96-3585-4ad3-94b1-c4f3dbe87176
    Get_QueryForCategory:
      summary: Get all Deny Policy assignments for category dentalrecord.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 1
        assignments:
          - assignmentId: 21694fb0-3019-4824-a34e-d4e1c031470e
            policyType: uspd
            for: category
            parameters:
              tid: 2-883110000092414
              oid: 1.2.276.0.76.4.51
              displayName: Zahnarztpraxis Norbert Freiherr Schomaker
              categoryId: dentalrecord
    Get_QueryForTID:
      summary: Get all Deny Policy assignments for telematik-id 1-883110000092404.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 2
        assignments:
          - assignmentId: 74343201-e669-4675-8414-3ce517220a3b
            policyType: usdp
            for: document
            parameters:
              tid: 1-883110000092404
              oid: 1.2.276.0.76.4.50
              displayName: Praxis Dr. Annamaria Heckhausén
              rootDocumentId: c4e17b20-ecee-4261-a51d-396b8e81bc27^^^^urn:gematik:iti:xds:2023:rootDocumentUniqueId
          - assignmentId: 7730578d-9380-47d6-ae82-d2c47ca399af
            policyType: usdp
            for: folder
            parameters:
              tid: 1-883110000092404
              oid: 1.2.276.0.76.4.50
              displayName: Praxis Dr. Annamaria Heckhausén
              folderUUID: urn:uuid:f9929ed6-1119-4dea-a48a-1cfe8117f7b7
    Get_QueryForRole:
      summary: Get all Deny Policy assignments for oid oid_zahnarztpraxis.
      value:
        query: 
          offset: 0
          limit: 50
          totalMatching: 1
        assignments:
          - assignmentId: 21694fb0-3019-4824-a34e-d4e1c031470e
            policyType: uspd
            for: category
            parameters:
              tid: 2-883110000092414
              oid: 1.2.276.0.76.4.51
              displayName: Zahnarztpraxis Norbert Freiherr Schomaker
              categoryId: dentalrecord

