openapi: 3.0.1
info:
  title: I_Information_Service_Accounts
  description: |-
    This interface provides operations for either health record relocation or health record merge
    among different Electronic Health Record System providers.<br/>

    **General conditions**:</br> 
    For all operations if applicable:
    - a section _Client_ in operation descriptions covers recommendations (informative) for clients.
    - a section _Provider_ in operation descriptions covers requirements for the server side. 

    **Prerequisites**:</br>
    This interface does not require a VAU channel/ user session or entitlements but a mutual 
    TLS connection instead.

    **Retry interval**:</br>
    Operation responses '409' Conflict and '500' Internal Error indicate temporary states.
    A retry may apply after a suitable period of waiting time. 

    **Request ID**:</br>
    Clients may provide a unique request identifier (X-Request-ID) with each request. 
    Given such a request identifier, providers must 
    - echo the exact same X-Request-ID value in the response header.
    - log the X-Request-ID in all operational logs related to that request.

    This _X-Request-ID_ for monitoring purposes should not be confused with the _requestId_
    used to identify relocation- or merge-sessions! 

  version: 2.0.0

  # version history:
  # ----------------
  # version 2.0.0
  #   - removed all account management operations (replaces by I_Account_Management)
  # version 1.9.0
  #   - added new error condition 409 - requestRejected to postMergePackageDeliveryIncident to allow rejection of a mergeAborted incident.
  #   - removed error condition for pending ePA-2.6 legacy migration (no longer supported) in startRelocation
  # version 1.8.0
  #   - added relocationRejected incident for postPackageDeliveryIncident to cover business rejections of relocation requests by exporting providers
  #   - added mergeRejected incident for postMergePackageDeliveryIncident to cover business rejections of merge requests by exporting providers
  # version 1.7.0
  #   - append identification of requesting health record system in startRelocation and startMerge
  #   - renamed merge incidents
  #   - added missing X-Request-ID to all responses
  # version 1.6.0
  #   - added operation getHealthRecordState
  #   - corrections in deleteExportPackage description to consider the new operation startre
  #   - editorial corrections (removed obsolete comments and doubled descriptions)
  # version 1.5.0
  #   - added operations for merge package exchange
  #   - editorial change: moved requestid (process identifier) to components section for separation from x-requestid (monitoring)
  # version 1.4.0
  #   - renamed all occurrences of state MAINTENANCE to INACCESSIBLE
  #   - added new status codes in getGeneralConsentDecision
  #   - improved description for startRelocation
  #   - improved description for deleteExportPackage
  #   - bugfix: added X-Request-ID to responses where missing
  # version 1.3.2
  #   - added status- and error code for state MAINTENANCE
  # version 1.3.1
  #   - clarification about condition for 404 noHealthRecord and 409 statusMismatch
  # version 1.3.0
  #   - mandatory X-Request-ID in all requests and responses
  #   - added isPrivateInsurance boolean to response of getProviderList
  # version 1.2.0
  #   - changed http-statuscode in operation postExportPackageIncident, putDownloadUrlForExportPAckage and postPackageDeliveryIncident to 204
  # version 1.1.2
  #   - bugfix for change in version 1.1.1 - added required statuscode 400 for response
  # version 1.1.2
  #   - added timestamp in response of getGeneralConsentDecision
  # version 1.1.1
  #   - changed path parameter insurantid to header parameter x-insurantid
  # version 1.1.0
  #   - changed http-statuscode in operation postExportPackageIncident, putDownloadUrlForExportPAckage and postPackageDeliveryIncident to 201
  # version 1.0.1
  #   - bugfixes
  # version 1.0.0
  #   - first release version
  # version 0.0.1
  #   - initial version for review

  contact:
    name: gematik GmbH
    url: 'http://www.gematik.de'
  
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"

servers:
  - url: https://epa-hst1.prod.epa4all.de/api

tags:
  - name: Account check
    description: |   
     Determines the health record state for a KVNR. The check is conducted across the entire health record system and also takes
     existing and potentially differing states for different insurances into account.   

  - name: ProviderList
    description: |
     Retrieve list of hosted insurances and FQDNs from other health record systems. 

paths:
  /information/api/v1/accounts/state:
    get:
      parameters:
        - $ref: '#/components/parameters/insurantid'
        - $ref: '#/components/parameters/x-requestid'
      tags:
        - Account check
      operationId: getHealthRecordState
      summary: (getHealthRecordState) Get the state of a health record.
      description: |
       Find all occurrences of health record states for a particular KVNR among all insurances of a health record provider.

       **Client**  
       A client (a health record system) shall always invoke this operation just before a health 
       record is set to state ACTIVATED to retrieve information about further (conflicting) activations
       of a health record for the same insurant. 
       
       A client shall not set a health record to ACTIVATED in case a conflict situation exists according to A_28686-*.  
      
       If a health record shall be set to ACTIVATED as final step of a health record relocation, a client shall invoke 
       this operation after the successful _deleteExportPackage_ operation.
       
       
       **Provider**  
       Find within the health record system every health record for the requested KVNR (_insurantid_) and determine
       the hosting insurance and its state. 
       The response shall include the states and associated insurance information of all occurrences found. 
       A health record is considered to exist when it has a state other than UNKNOWN (meaning: completely unknown).
       
       Internal or proprieary states used by the health record system (e.g. substates of INACCESSIBLE) shall be mapped in the response 
       to the specified states (specifies states are: INITIALIZED, ACTIVATED, SUSPENDED and INACCESSIBLE).

       
       | Conditions | Status code | Error code | Remarks |
       |------------|-------------|------------|---------|
       | Successful operation | 200 |||
       | Request does not match schema | 400 | malformedRequest ||
       | No mutual TLS channel used | 403 | accessDenied ||
       | KVNR (insurant) unknown | 404 | noResource | _insurantid_ unknown |
       | Any other error | 500 | internalError ||

       </br>
       | Postconditions                        | Remarks |
       |---------------------------------------|---------|
       | none ||

      responses:
        '200':
          description: Ok.
          headers:
            X-Request-ID:
              $ref: '#/components/headers/xrequestid'
          content:
            application/json:
              examples: 
                One suspended record state found:
                  value:
                    records:    
                      - insurance: 'Muster Krankenkasse A' 
                        insuranceId: '123456789'
                        recordState: SUSPENDED                      
                One conflicting record state found:
                  value:
                    records:    
                      - insurance: 'Muster Krankenkasse B'
                        insuranceId: '987654321'
                        recordState: ACTIVATED    
                Multiple and conflicting record state found:
                  value:
                    records:    
                      - insurance: 'Muster Krankenkasse C'
                        insuranceId: '246898642'
                        recordState: INITIALIZED                       
                      - insurance: 'Muster Krankenkasse'
                        insuranceId: '123456789'
                        recordState: SUSPENDED    
              schema:
                description: 'List of all health record occurences associated to _insurantid_ '
                type: object
                properties:
                  records:
                    description: The state(s) and associated insurance information of the health record(s).
                    type: array
                    items:
                      $ref: '#/components/schemas/RecordInformationType'                
        '400':
          $ref: '#/components/responses/Error400BadRequest'
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '404':
          $ref: "#/components/responses/Error404NotFound"
        '500':
          $ref: '#/components/responses/Error500InternalError'

  /information/api/v1/providerlist:
    parameters:
    - $ref: '#/components/parameters/x-requestid'
    get:
      tags:
        - ProviderList
      operationId: getProviderList
      summary: (getProviderList) get a list of health care providers
      description: |
       Get a list of health care providers and FQDNs of Access Gateways for ePA-FdVs.

       **Client**:</br>
       A client shall invoke this operation for each health record system and collect 
       the received data. A client shall also add it's own list and finally maintain 
       a complete list of insurance company / FQDN entries for user client localization
       requirements.
       A client shall also store each insurance's type (statutory/private) to be able to cater to
       type specific needs.

       **Provider**:</br>
       Prepare a list of all hosted insurances including their FQDNs and type (statutory/private).

       | Conditions | Status code | Error code | Remarks |
       |------------|-------------|------------|---------|
       | Successful operation | 200 |||
       | No mutual TLS channel used | 403 | accessDenied ||
       | Any other error | 500 | internalError ||

       </br>
       | Postconditions                        | Remarks |
       |---------------------------------------|---------|
       | none ||

      responses:
        '200':
          description: Ok.
          headers:
            X-Request-ID:
              $ref: '#/components/headers/xrequestid'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    insurance:
                      type: string
                      description: name of insurance
                    fqdn:
                      type: string
                      description: FQDN
                    isPrivateInsurance:
                      type: boolean
                      description: indicates the insurance type, private (true) or statutory (false)
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '500':
          $ref: '#/components/responses/Error500InternalError'

components:
  headers:
    xrequestid:
      description: Request identifier as provided by the client.
      schema:
       $ref: '#/components/schemas/RequestIdType'
  parameters:
    insurantid:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: '#/components/schemas/InsurantIdType'
    x-requestid:
      name: X-Request-ID
      in: header
      description: Optional monitoring request identifier
      schema:
        $ref: '#/components/schemas/RequestIdType'
    requestid:
      name: requestid
      in: path
      description: Process request identifier
      required: true
      schema:
        $ref: '#/components/schemas/RequestIdType'

  responses:
    Error400BadRequest:
      description: Bad Request.
      headers:
        X-Request-ID:
          $ref: '#/components/headers/xrequestid'
      content:
        application/json:
          example:
            errorCode: malformedRequest
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error403Forbidden:
      description: Forbidden.
      headers:
        X-Request-ID:
          $ref: '#/components/headers/xrequestid'
      content:
        application/json:
          example:
            errorCode: accessDenied
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error404NotFound:
      description: Not found.
      headers:
        X-Request-ID:
          $ref: '#/components/headers/xrequestid'
      content:
        application/json:
          example:
            errorCode: noResource
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error500InternalError:
      description: Internal Server Error
      headers:
        X-Request-ID:
          $ref: '#/components/headers/xrequestid'
      content:
        application/json:
          example:
            errorCode: internalError
          schema:
            $ref: '#/components/schemas/ErrorType'

  schemas:
    RecordInformationType:
      description: 'State and associated insurance of a health record.'
      type: object
      properties:
        insurance:
          description: The name of the insurance hosting the health record.
          type: string
          example: 'Muster Krankenkasse'
        insuranceId:
          description: The IK-Number of the insurance hosting the health record. 
          type: string
          example: '123456789'  
        recordState:
          description: The state of the health record.  
          type: string
          enum:
            - INITIALIZED
            - ACTIVATED
            - INACCESSIBLE
            - SUSPENDED
      required:
        - insurance
        - recordState
    InsurantIdType:
      description: |-
        The health record identifier. 
        For today the record identifier equals the insurant id (KVNR). The record identifier does not include any home community id.
      type: string
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    RequestIdType:
      type: string
      format: uuid
      example: '3dc69bad-6711-4983-b42c-5834f569c6ec'
    ErrorType:
      description: "Error object with additional information about the occurred error"
      type: object
      properties:
        errorCode:
          description: "Error condition specifier"
          type: string
        errorDetail:
          description: "Additional details regarding the error condition"
          type: string
      required:
        - errorCode
